spring.application.name=react_semi_back

#server port
server.port=9999

#oracle 
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@1.223.77.178:15211/XEPDB1
spring.datasource.username=TEAM4_DB
spring.datasource.password=4444

#mybatis 
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/**.xml
mybatis.type-aliases-package=kr.co.iei
mybatis.configuration.jdbc-type-for-null=NULL

#email 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=youngminLee0428
spring.mail.password=iaklbqqbzvmjwdes
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#jwt -> expire-hour : token to endtime set
jwt.secret-key=kh.web.secret.code.long.long.long.aaaa.bbb.ccc
jwt.expire-hour=1

#file upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-part-count=50


#file upload location
file.root=//192.168.31.24/project/upload/web/

